// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: mydemo_conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MydemoConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   *Database `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Database *Server   `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
}

func (x *MydemoConfig) Reset() {
	*x = MydemoConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mydemo_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MydemoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MydemoConfig) ProtoMessage() {}

func (x *MydemoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mydemo_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MydemoConfig.ProtoReflect.Descriptor instead.
func (*MydemoConfig) Descriptor() ([]byte, []int) {
	return file_mydemo_conf_proto_rawDescGZIP(), []int{0}
}

func (x *MydemoConfig) GetServer() *Database {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *MydemoConfig) GetDatabase() *Server {
	if x != nil {
		return x.Database
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grpc string `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mydemo_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_mydemo_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_mydemo_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() string {
	if x != nil {
		return x.Grpc
	}
	return ""
}

type Database struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mysql string `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
}

func (x *Database) Reset() {
	*x = Database{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mydemo_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_mydemo_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_mydemo_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Database) GetMysql() string {
	if x != nil {
		return x.Mysql
	}
	return ""
}

var File_mydemo_conf_proto protoreflect.FileDescriptor

var file_mydemo_conf_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x79, 0x64, 0x65, 0x6d, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x22,
	0x6c, 0x0a, 0x0c, 0x4d, 0x79, 0x64, 0x65, 0x6d, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x2c, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2e, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x1c, 0x0a,
	0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x20, 0x0a, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x42, 0x1b, 0x5a,
	0x19, 0x6d, 0x79, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mydemo_conf_proto_rawDescOnce sync.Once
	file_mydemo_conf_proto_rawDescData = file_mydemo_conf_proto_rawDesc
)

func file_mydemo_conf_proto_rawDescGZIP() []byte {
	file_mydemo_conf_proto_rawDescOnce.Do(func() {
		file_mydemo_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_mydemo_conf_proto_rawDescData)
	})
	return file_mydemo_conf_proto_rawDescData
}

var file_mydemo_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mydemo_conf_proto_goTypes = []interface{}{
	(*MydemoConfig)(nil), // 0: kratos.api.MydemoConfig
	(*Server)(nil),       // 1: kratos.api.Server
	(*Database)(nil),     // 2: kratos.api.Database
}
var file_mydemo_conf_proto_depIdxs = []int32{
	2, // 0: kratos.api.MydemoConfig.server:type_name -> kratos.api.Database
	1, // 1: kratos.api.MydemoConfig.database:type_name -> kratos.api.Server
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mydemo_conf_proto_init() }
func file_mydemo_conf_proto_init() {
	if File_mydemo_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mydemo_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MydemoConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mydemo_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mydemo_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mydemo_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mydemo_conf_proto_goTypes,
		DependencyIndexes: file_mydemo_conf_proto_depIdxs,
		MessageInfos:      file_mydemo_conf_proto_msgTypes,
	}.Build()
	File_mydemo_conf_proto = out.File
	file_mydemo_conf_proto_rawDesc = nil
	file_mydemo_conf_proto_goTypes = nil
	file_mydemo_conf_proto_depIdxs = nil
}
